title: Lingo
tagline: A BDD-style assertion library for .NET

author:
    name: Sam Singer Noedel

github: https://github.com/delta62/lingo
license: https://github.com/delta62/lingo/blob/master/LICENSE

markdown: redcarpet
