title: Lingo
tagline: A BDD-style assertion library for .NET

baseurl: http://delta62.github.io/lingo

author:
    name: Sam Singer Noedel

github: https://github.com/delta62/lingo
license: https://github.com/delta62/lingo/blob/master/LICENSE

markdown: kramdown
kramdown:
    input: GFM
    toc_levels: [ 2 ]
    coderay_default_lang: java
    coderay_line_numbers: nil
