title: Lingo
tagline: A BDD-style assertion library for .NET

baseurl: http://delta62.github.io/lingo

github: https://github.com/delta62/lingo
license: https://github.com/delta62/lingo/blob/master/LICENSE

markdown: kramdown
kramdown:
    input: GFM
    toc_levels: [ 2 ]
    hard_wrap: false
    coderay_line_numbers: nil
